### PR TITLE
Docker debian

### PR DESCRIPTION
**Pull request by cebe**
created a Dockerfile for a debian environment.

- all things needed to compile PHP are pre-installed
- a  `switchphp` command is included which can be used to switch between different php versions (also different configurations) on the system and play with them

### CODE REVIEW

**Comment by salathe** [comment]
The readme could do with much more explanation of the intended workflow using this image, especially making it clear that there is no PHP source code, nor a PHP "7" version of the php binary, available to containers (you have to do all that yourself). 

I came here expecting a dockerfile for an image that had all the bells and whistles I need to jump right in to building, debugging, documenting PHP and extensions. The image here doesn't really provide much beyond the "offical" PHP docker images.

The dockerfile too seems odd; why go to the trouble of including the bash (with all those aliases!) and git configurations? I understand that you might like those configurations, but if you want to customise the experience inside containers, it would be better to generate your own image (from this one).

So what would I like? Personally, I'd like a docker image that has an up-to-date build of PHP 7 available (ideally, with the source code and a build environment) out-of-the-box.  Something that I can fire code and see what's what.  On top of that, the ability to make simple images based on this for playing with extensions, running tests, etc.  That should really be something we could do with a couple of lines in a new dockerfile based on the base image provided here.

**Comment by cebe** [comment]
Thanks for your feedback. Will try to improve the readme to make it more clear.

> I came here expecting a dockerfile for an image that had all the bells and whistles I need to jump right in to building, debugging, documenting PHP and extensions.

the idea of a docker container is to have a separate environment that you can play in so that you do not have to install (possibly conflicting) libraries natively on your system. Changes that are made inside the container ususally do not persists and because you want to change code/docs of the PHP repo these have to be mounted from your system into the container so that they persist over multiple starts.

> The image here doesn't really provide much beyond the "offical" PHP docker images.

If you mean the images from docker hub, these are meant to run php scripts on versions from the system packages. This one is meant to be used for building php and playing with it.


> The dockerfile too seems odd; why go to the trouble of including the bash (with all those aliases!) and git configurations? I understand that you might like those configurations, but if you want to customise the experience inside containers, it would be better to generate your own image (from this one).

You can of course use this thing and customize it further. I like to have a useful git config and bashrc when I switch into the docker container, otherwise it would be much slower to work with. If you want another .bashrc or git config you can adjust them to your needs I just thought to provide a good default.

**Comment by svpernova09** [comment]
@cebe 

Thanks for the Docker stuff, always good to have more platforms for people to test stuff.

I think (for now anyway) it may make sense to have these type things in their own repos and have gophp7-ext link to them (Like I've done with http://gophp7.org/gophp7-ext/development-platforms.html) instead of housing them in this repo.

I'd be all for even having sections of that site be dedicated to better usage instructions. That fits really well with the our stated goals.

**Comment by lornajane** [comment]
Closing due to inactivity

**Pull request closed without merging**
