### PR TITLE
Brazilian portuguese translation

### PR DESCRIPTION
**Pull request by vinicius-ianni**
As told in the email sent to lorna jane, i've translated the content for brazilian portuguese, in order to facilitate access to the project by Brazilian programmers, might serve as a decoy for those who have not been interested in participate in projects related to php or open source in general, or for those has lazy to read (relatively) long documents (believe, they exist)

### CODE REVIEW

**Comment by lornajane** [comment]
I would really like us to have translations of the content on our site, but this pull request doesn't merge into our existing site.  It's a github pages site, so the branch should originate from and request a pull request to the gh-pages branch.  I believe Jekyll can be multilingual but we should look into how to set up the content to do this - otherwise I'm afraid it simply won't be seen by its readers.

Can someone update this pull request so we can accept the translated content?  I think we need some more input here.

**Comment by vinicius-ianni** [comment]
Sorry about the mess, i didn't had any idea about how github pages worked, next time i do right :) (i hope....)

Anyway, i put myself at your disposal to translate any text or documents to brazilian portuguese.

**Comment by auroraeosrose** [comment]
https://github.com/jekyll/jekyll/issues/389 looks like doing multiple languages might be a bit outside of github pages for now?  Not sure how to get around this or make it work though...

**Comment by lornajane** [comment]
Can we just get the content into some pages on the site for now?  So a pull request that forks from gh-pages and works when tested with Jekyll locally?  I think it's useful to have - but we can't merge the pull request in it's current form so I'll close for now and await an updated one.

**Pull request closed without merging**
